apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapas.fullname" . }}
  labels:
    {{- include "mapas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.nginx.enabled }}http{{ else }}php-fpm{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "mapas.selectorLabels" . | nindent 4 }}
