name: cypress-ci

on:
  pull_request:
    branch:
      - 'main'
      - 'feature/upgrade-cypress'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Instala as dependÃªncias
        run: cd src/ && npm install

      - name: Executa todos os testes do Cypress
        run: npx cypress run --spec "src/cypress/e2e/**/*.js"
